#!/usr/bin/env python3
"""Write segments-checkin/LINES.md: each clip, its length, and the line that goes on it.

Generated from CHECKIN-1.md and the manifest the recorder wrote, so the pairing cannot drift from
either. The Stocklana cut had this table by hand and it described a different edit for a day.

    python3 video/lines.py
"""
import io, json, os, re

SEG = "video/segments-checkin"
md = io.open("video/CHECKIN-1.md", encoding="utf-8").read()
manifest = json.load(open(f"{SEG}/manifest.json"))

scenes = []
for m in re.finditer(r"^### (\d+) — ([^·\n]+?)\s*(?:·[^\n]*)?$\n\n((?:^> ?.*\n)+)", md, re.M):
    body = re.sub(r"^> ?", "", m.group(3), flags=re.M).strip()
    scenes.append((m.group(2).strip(), body))

if len(scenes) != len(manifest):
    raise SystemExit(f"  {len(scenes)} scenes in the script, {len(manifest)} clips on disk")

L = ["# Check-in 1 — the cut, clip by clip",
     "",
     "Three clips in `segments-checkin/`, **silent**, cut at the boundaries the recorder logged.",
     "Generate the voice per clip and lay it back in order; the clip length is the budget, and the",
     "delivery should finish a little before the picture does.",
     "",
     "Generated by `python3 video/lines.py` from [`../CHECKIN-1.md`](../CHECKIN-1.md) and",
     "`manifest.json` — neither the lengths nor the lines are typed here.",
     "",
     "| clip | length | words | pace |",
     "|---|---|---|---|"]
for e, (title, body) in zip(manifest, scenes):
    w = len(body.split())
    pace = round(w / max(e["seconds"] - 0.6, 0.1) * 60)
    L.append("| `%s` | %.1fs | %d | %d wpm |" % (e["file"], e["seconds"], w, pace))
L += ["",
      "Pace is words over the clip minus 0.6s of tail. Over 180 wpm is reading without pauses.",
      ""]
for e, (title, body) in zip(manifest, scenes):
    L += ["## `%s` — %s" % (e["file"], title), "", "> " + body.replace("\n", "\n> "), ""]

io.open(f"{SEG}/LINES.md", "w", encoding="utf-8").write("\n".join(L))
print(f"  wrote {SEG}/LINES.md — {len(scenes)} clips")
