#!/usr/bin/env python3
"""Write a cut's LINES.md: each clip, its length, and the line that goes on it.

Generated from the script and the manifest the recorder wrote, so the pairing cannot drift from
either. The Stocklana cut had this table by hand and it described a different edit for a day.

    python3 video/lines.py checkin         # -> segments-checkin/LINES.md
    python3 video/lines.py presentation    # -> segments-presentation/LINES.md

One generator for both scripted cuts, the way split.sh is one splitter. A copy per cut is the
failure this file exists to prevent; making one here would be the joke writing itself.
"""
import io, json, os, re, sys

# The check-in entry names CHECKIN-1 because segments-checkin holds CHECKIN-1's clips, and those
# were submitted. A later check-in is a DIFFERENT cut with its own directory, so it is passed in
# rather than silently replacing the one on disk:
#
#     CHECKIN_DOC=video/CHECKIN-2.md CHECKIN_SEG=video/segments-checkin-2 \
#       python3 video/lines.py checkin
#
# Defaults unchanged, so nothing that already passes starts failing.
CHECKIN_DOC = os.environ.get("CHECKIN_DOC", "video/CHECKIN-1.md")
CHECKIN_SEG = os.environ.get("CHECKIN_SEG", "video/segments-checkin")
CHECKIN_TITLE = "Check-in " + re.search(r"(\d+)", CHECKIN_DOC).group(1)

CUTS = {
    "checkin": (CHECKIN_DOC, CHECKIN_SEG, CHECKIN_TITLE, "Three clips"),
    "presentation": ("video/CWF-PRESENTATION.md", "video/segments-presentation",
                     "The CWF presentation, rough cut", "Eight clips"),
}
cut = sys.argv[1] if len(sys.argv) > 1 else "checkin"
if cut not in CUTS:
    raise SystemExit("  usage: lines.py [%s]" % "|".join(CUTS))
DOC, SEG, TITLE, COUNT = CUTS[cut]

md = io.open(DOC, encoding="utf-8").read()
manifest = json.load(open(f"{SEG}/manifest.json"))

# Declared silence is part of the picture and not part of the pace — the same rule pace.py
# follows. Without it, a scene built around a five-second gap reports 90 wpm and the person
# recording the voice reads it as room they have. They do not: the gap is the scene.
scenes = []
for m in re.finditer(r"^### (\d+) — ([^·\n]+?)\s*(?:·[^\n]*)?$\n\n((?:^> ?.*\n)+)", md, re.M):
    body = re.sub(r"^> ?", "", m.group(3), flags=re.M).strip()
    pause = re.search(r"\+\s*([\d.]+)\s*s silence", m.group(0).split("\n")[0])
    scenes.append((m.group(2).strip(), body, float(pause.group(1)) if pause else 0.0))

if len(scenes) != len(manifest):
    raise SystemExit(f"  {len(scenes)} scenes in the script, {len(manifest)} clips on disk")

L = ["# %s — the cut, clip by clip" % TITLE,
     "",
     "%s in `%s/`, **silent**, cut at the boundaries the recorder logged." % (COUNT, os.path.basename(SEG)),
     "Generate the voice per clip and lay it back in order; the clip length is the budget, and the",
     "delivery should finish a little before the picture does.",
     "",
     "Generated by `python3 video/lines.py %s` from [`../%s`](../%s) and" % (cut, os.path.basename(DOC), os.path.basename(DOC)),
     "`manifest.json` — neither the lengths nor the lines are typed here.",
     "",
     "| clip | length | words | pace |",
     "|---|---|---|---|"]
for e, (title, body, pause) in zip(manifest, scenes):
    w = len(body.split())
    pace = round(w / max(e["seconds"] - 0.6 - pause, 0.1) * 60)
    held = "%.1fs" % e["seconds"] + (" (%gs of it silent)" % pause if pause else "")
    L.append("| `%s` | %s | %d | %d wpm |" % (e["file"], held, w, pace))
L += ["",
      "Pace is words over the clip minus 0.6s of tail and any declared silence. Over 180 wpm is",
      "reading without pauses.",
      ""]
for e, (title, body, pause) in zip(manifest, scenes):
    L += ["## `%s` — %s" % (e["file"], title), "", "> " + body.replace("\n", "\n> "), ""]

# --stdout prints instead of writing, so a check can compare the file on disk against what this
# would produce without rewriting it. A check that repairs what it is checking reports success on
# a repository that was wrong a moment earlier.
out = "\n".join(L)
if "--stdout" in sys.argv:
    sys.stdout.write(out)
    raise SystemExit(0)
io.open(f"{SEG}/LINES.md", "w", encoding="utf-8").write(out)
print(f"  wrote {SEG}/LINES.md — {len(scenes)} clips")
