#!/usr/bin/env bash
# Regenerate web/proofs.json for a live confidential account.
#
#   ./scripts/refresh-proofs.sh <token_account> [threshold_units] [keys.json]
#
# The page replays these two transactions and the ZK program checks them while a visitor watches.
# They are self-contained - the program never reads the account to verify them - so the page also
# pins the ciphertext they were made over and compares it against the live account before it treats
# a pass as meaningful. That pin is `available_balance` below; without it a devnet reset would leave
# the page green and hollow.
#
# Until 09-15 this file was assembled by hand, which meant the recovery written in DURABILITY.md
# had a step nobody could run.
set -euo pipefail
cd "$(dirname "$0")/.."
RPC="${RPC:-https://api.devnet.solana.com}"
ACC="${1:?usage: refresh-proofs.sh <token_account> [threshold_units] [keys.json]}"
UNITS="${2:-100000}"
KEYS="${3:-account-keys.json}"
THRESHOLD=$(( UNITS * 100000000 ))

rpc() { curl -s "$RPC" -H 'Content-Type: application/json' -d "$1"; }

read -r DEC AVAIL MINT < <(rpc "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getAccountInfo\",\"params\":[\"$ACC\",{\"encoding\":\"jsonParsed\",\"commitment\":\"confirmed\"}]}" \
| python3 -c "
import sys, json
i = json.load(sys.stdin)['result']['value']['data']['parsed']['info']
ct = next(e['state'] for e in i['extensions'] if e['extension'] == 'confidentialTransferAccount')
print(ct['decryptableAvailableBalance'], ct['availableBalance'], i['mint'])
")

PAYER=$(rpc '{"jsonrpc":"2.0","id":1,"method":"getVoteAccounts","params":[{"keepUnstakedDelinquents":false}]}' \
  | python3 -c "import sys,json;print(json.load(sys.stdin)['result']['current'][0]['nodePubkey'])")
BH=$(rpc '{"jsonrpc":"2.0","id":1,"method":"getLatestBlockhash","params":[{"commitment":"finalized"}]}' \
  | python3 -c "import sys,json;print(json.load(sys.stdin)['result']['value']['blockhash'])")

TMP=$(mktemp)
cargo run --quiet -p confide-ct --bin prove-collateral -- "$KEYS" "$DEC" "$AVAIL" "$THRESHOLD" "$BH" "$PAYER" > "$TMP"
TX_EQ=$(sed -n '1p' "$TMP"); TX_RANGE=$(sed -n '2p' "$TMP"); rm -f "$TMP"

# Refuse to write a file whose proofs do not actually pass. A proofs.json that renders red is worse
# than none: the page would report a failure of the chain rather than of this script.
for TX in "$TX_EQ" "$TX_RANGE"; do
  rpc "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"simulateTransaction\",\"params\":[\"$TX\",{\"sigVerify\":false,\"replaceRecentBlockhash\":true,\"encoding\":\"base64\"}]}" \
  | python3 -c "
import sys, json
v = json.load(sys.stdin)['result']['value']
if v['err'] is not None:
    print('  proof rejected:', v['err']); raise SystemExit(1)
"
done

ACC="$ACC" MINT="$MINT" UNITS="$UNITS" AVAIL="$AVAIL" TX_EQ="$TX_EQ" TX_RANGE="$TX_RANGE" \
python3 -c "
import json, os, datetime
json.dump({
  'account': os.environ['ACC'],
  'threshold_units': int(os.environ['UNITS']),
  'equality_tx': os.environ['TX_EQ'],
  'range_tx': os.environ['TX_RANGE'],
  'note': 'Proofs generated by scripts/prove-collateral.sh over the account above. Regenerate with scripts/refresh-proofs.sh.',
  'available_balance': os.environ['AVAIL'],
  'mint': os.environ['MINT'],
  'generated_utc': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d'),
}, open('web/proofs.json','w'), indent=1)
print('  wrote web/proofs.json')
print('  account          ', os.environ['ACC'])
print('  mint             ', os.environ['MINT'])
print('  ciphertext pinned', os.environ['AVAIL'][:44] + '…')
"
